### Create new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "benbanda07@gmail.com",
    "password": "123456"
}
### Get One User
GET http://localhost:3000/auth/1

### Get Users by email
GET http://localhost:3000/auth?email=benbanda07@gmail.com

### Delete One User
DELETE http://localhost:3000/auth/1

### Update User
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "password": "654321"
}